FROM python:3.10-slim-buster
# FROM python:3.9.13-slim-buster

WORKDIR /app

COPY . /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 5000
CMD ["python", "-u", "workflow.py"]